apply restart daemon script at others in linux package.

diff --git a/build/packaging/linux/bin/kbnd b/build/packaging/linux/bin/kbnd
--- a/build/packaging/linux/bin/kbnd
+++ b/build/packaging/linux/bin/kbnd
@@ -8,6 +8,7 @@ STOP_TIMEOUT=10 # seconds to wait for a clean exit
 source $CONF/kbnd.conf
 
 pidfile=$CMD_HOME/kbnd.pid
+auto_restart_daemon_pidfile=$DATA_DIR/restart_daemon.pid
 
 __pid_run() {
     unset pid
@@ -17,6 +18,17 @@ __pid_run() {
     PID_NUM=$(eval "cat $pidfile")
     if [[ ! -z "$PID_NUM" ]]; then
         export pid=$(eval "ps -p $PID_NUM -o pid=")
+    fi
+}
+
+__auto_restart_daemon_pid_run() {
+    unset auto_restart_daemon_pid
+    if [ ! -f $auto_restart_daemon_pidfile ]; then
+        return
+    fi
+    AUTO_RESTART_DAEMON_PID_NUM=$(eval "cat $auto_restart_daemon_pidfile")
+    if [[ ! -z "$AUTO_RESTART_DAEMON_PID_NUM" ]]; then
+        export auto_restart_daemon_pid=$(eval "ps -p $AUTO_RESTART_DAEMON_PID_NUM -o pid=")
     fi
 }
 
@@ -33,7 +45,70 @@ __kill_timeout() {
     kill -9 $PIDNUM && echo "Killed"
 }
 
-start() {
+#------------------------Related Auto restart daemon functions-----------------------------
+__auto_restart_daemon() {
+    local backOffTime=$AUTO_RESTART_INTERVAL
+    local coeff=2
+    while :
+    do
+        sleep 1
+        __pid_run
+        if [ -z "$pid" ]; then
+            echo "INFO[`date`] node[${PID_NUM}] is down"
+            if [ -f $pidfile ]; then
+                echo "INFO[`date`] remove redundant pid file"
+                rm -f ${pidfile}
+            fi
+            echo "INFO[`date`] Sleep for backOffTime.... ${backOffTime} seconds."
+            sleep $backOffTime
+            echo "INFO[`date`] -------------------> start network"
+            start_node
+            echo "INFO[`date`] -------------------> start network"
+            backOffTime=$(echo $backOffTime $coeff | awk '{printf "%.1f\n",$1*$2}')
+
+            echo "INFO[`date`] backOffTime = ${backOffTime}, Restarted node pid = ${PID_NUM}"
+            PID_NUM=$(eval "cat $pidfile")
+            echo ""
+        fi
+    done
+}
+
+start_auto_restart_daemon() {
+    __auto_restart_daemon_pid_run
+    if [ -z $auto_restart_daemon_pid ]; then
+        __auto_restart_daemon >> ${LOG_DIR}/restart_daemon.out 2>&1 &
+        disown
+        AUTO_RESTART_DAEMON_PID_NUM=$!
+        AUTO_RESTART_DAEMON_RETVAL=$?
+
+        set +f
+        if [ $AUTO_RESTART_DAEMON_RETVAL = 0 ]; then
+            echo $AUTO_RESTART_DAEMON_PID_NUM > ${auto_restart_daemon_pidfile}
+            echo "Success to start auto restart daemon."
+        else
+            echo "Fail to start auto restart daemon."
+        fi
+    fi
+}
+
+stop_auto_restart_daemon() {
+    __auto_restart_daemon_pid_run
+    [ -z "$auto_restart_daemon_pid" ] && echo "auto restart daemon is not running" && return
+    echo -n "Shutting down auto restart daemon:  "
+    __kill_timeout $(eval "cat ${auto_restart_daemon_pidfile}") && rm -f ${auto_restart_daemon_pidfile}
+}
+
+status_auto_restart_daemon() {
+    __auto_restart_daemon_pid_run
+    if [ -n "$auto_restart_daemon_pid" ]; then
+        echo "auto restart daemon is running."
+    else
+        echo "auto restart daemon is down."
+    fi
+}
+
+#------------------------Related to Klaytn node functions-----------------------------
+start_node() {
     __pid_run
     [ -n "$pid" ] && echo "kbnd already running...[$pid]" && return
 
@@ -92,19 +167,47 @@ start() {
     return $RETVAL
 }
 
-stop() {
+stop_node() {
     __pid_run
     [ -z "$pid" ] && echo "kbnd is not running" && return
     echo -n "Shutting down kbnd:  "
     __kill_timeout $(eval "cat ${pidfile}") && rm -f ${pidfile}
 }
 
-status() {
+status_node() {
     __pid_run
     if [ -n "$pid" ]; then
         echo "kbnd is running"
     else
         echo "kbnd is down"
+    fi
+}
+
+#--------------------- Public functions --------------------------
+start() {
+    if [ ! -d $LOG_DIR ]; then
+        mkdir -p $LOG_DIR
+    fi
+
+    if [ ! -z $AUTO_RESTART_NODE ] && [[ $AUTO_RESTART_NODE -eq 1 ]]; then
+        start_auto_restart_daemon
+    else
+        start_node
+    fi
+}
+
+stop() {
+    if [ ! -z $AUTO_RESTART_NODE ] && [[ $AUTO_RESTART_NODE -eq 1 ]]; then
+        stop_auto_restart_daemon
+    fi
+    stop_node
+}
+
+
+status() {
+    status_node
+    if [ ! -z $AUTO_RESTART_NODE ] && [[ $AUTO_RESTART_NODE -eq 1 ]]; then
+        status_auto_restart_daemon
     fi
 }
 
