apply restart daemon script at kend

diff --git a/build/packaging/linux/bin/kend b/build/packaging/linux/bin/kend
--- a/build/packaging/linux/bin/kend
+++ b/build/packaging/linux/bin/kend
@@ -1,3 +1,4 @@
+#linux kend
 #!/usr/bin/env bash
 
 BIN=$(cd "$(dirname $0)"; pwd)
@@ -20,6 +21,7 @@ if [ ! -d $DATA_DIR ]; then
 fi
 
 pidfile=$DATA_DIR/kend.pid
+auto_restart_daemon_pidfile=$DATA_DIR/restart_daemon.pid
 
 __pid_run() {
     unset pid
@@ -29,6 +31,17 @@ __pid_run() {
     PID_NUM=$(eval "cat $pidfile")
     if [[ ! -z "$PID_NUM" ]]; then
         export pid=$(eval "ps -p $PID_NUM -o pid=")
+    fi
+}
+
+__auto_restart_daemon_pid_run() {
+    unset auto_restart_daemon_pid
+    if [ ! -f $auto_restart_daemon_pidfile ]; then
+        return
+    fi
+    AUTO_RESTART_DAEMON_PID_NUM=$(eval "cat $auto_restart_daemon_pidfile")
+    if [[ ! -z "$AUTO_RESTART_DAEMON_PID_NUM" ]]; then
+        export auto_restart_daemon_pid=$(eval "ps -p $AUTO_RESTART_DAEMON_PID_NUM -o pid=")
     fi
 }
 
@@ -44,6 +57,70 @@ __kill_timeout() {
     done
     kill -9 $PIDNUM && echo "Killed"
 }
+
+#------------------------Related Auto restart daemon functions-----------------------------
+__auto_restart_daemon() {
+    local backOffTime=$AUTO_RESTART_INTERVAL
+    local coeff=2
+    while :
+    do
+        sleep 1
+        __pid_run
+        if [ -z "$pid" ]; then
+            echo "INFO[`date`] node[${PID_NUM}] is down"
+            if [ -f $pidfile ]; then
+                echo "INFO[`date`] remove redundant pid file"
+                rm -f ${pidfile}
+            fi
+            echo "INFO[`date`] Sleep for backOffTime.... ${backOffTime} seconds."
+            sleep $backOffTime
+            echo "INFO[`date`] -------------------> start network"
+            start_node
+            echo "INFO[`date`] -------------------> start network"
+            backOffTime=$(echo $backOffTime $coeff | awk '{printf "%.1f\n",$1*$2}')
+
+            echo "INFO[`date`] backOffTime = ${backOffTime}, Restarted node pid = ${PID_NUM}"
+            PID_NUM=$(eval "cat $pidfile")
+            echo ""
+        fi
+    done
+}
+
+start_auto_restart_daemon() {
+    __auto_restart_daemon_pid_run
+    if [ -z $auto_restart_daemon_pid ]; then
+        __auto_restart_daemon >> ${LOG_DIR}/restart_daemon.out 2>&1 &
+        disown
+        AUTO_RESTART_DAEMON_PID_NUM=$!
+        AUTO_RESTART_DAEMON_RETVAL=$?
+
+        set +f
+        if [ $AUTO_RESTART_DAEMON_RETVAL = 0 ]; then
+            echo $AUTO_RESTART_DAEMON_PID_NUM > ${auto_restart_daemon_pidfile}
+            echo "Success to start auto restart daemon."
+        else
+            echo "Fail to start auto restart daemon."
+        fi
+    fi
+}
+
+stop_auto_restart_daemon() {
+    __auto_restart_daemon_pid_run
+    [ -z "$auto_restart_daemon_pid" ] && echo "auto restart daemon is not running" && return
+    echo -n "Shutting down auto restart daemon:  "
+    __kill_timeout $(eval "cat ${auto_restart_daemon_pidfile}") && rm -f ${auto_restart_daemon_pidfile}
+}
+
+status_auto_restart_daemon() {
+    __auto_restart_daemon_pid_run
+    if [ -n "$auto_restart_daemon_pid" ]; then
+        echo "auto restart daemon is running."
+    else
+        echo "auto restart daemon is down."
+    fi
+}
+
+#------------------------Related to Klaytn node functions-----------------------------
 
 __check_option() {
     if [ ! -d $LOG_DIR ]; then
@@ -246,7 +323,7 @@ __check_option() {
     fi
 }
 
-start() {
+start_node() {
     __pid_run
     [ -n "$pid" ] && echo "kend already running...[$pid]" && return
 
@@ -271,6 +348,33 @@ start() {
     return $RETVAL
 }
 
+stop_node() {
+    __pid_run
+    [ -z "$pid" ] && echo "kend is not running" && return
+    echo -n "Shutting down kend: "
+    __kill_timeout $(eval "cat ${pidfile}") && rm -f ${pidfile}
+}
+
+status_node() {
+    __pid_run
+    if [ -n "$pid" ]; then
+        echo "kend is running"
+    else
+        echo "kend is down"
+    fi
+}
+
+#--------------------- Public functions --------------------------
+start() {
+    start_node
+    RET=$?
+    if [ $RET = 0 ]; then
+        if [ ! -z $AUTO_RESTART_NODE ] && [[ $AUTO_RESTART_NODE -eq 1 ]]; then
+            start_auto_restart_daemon
+        fi
+    fi
+}
+
 start_docker() {
     echo -n "Starting kend: "
     __check_option
@@ -280,20 +384,20 @@ start_docker() {
 }
 
 stop() {
-    __pid_run
-    [ -z "$pid" ] && echo "kend is not running" && return
-    echo -n "Shutting down kend: "
-    __kill_timeout $(eval "cat ${pidfile}") && rm -f ${pidfile}
+    if [ ! -z $AUTO_RESTART_NODE ] && [[ $AUTO_RESTART_NODE -eq 1 ]]; then
+        stop_auto_restart_daemon
+    fi
+    stop_node
 }
 
+
 status() {
-    __pid_run
-    if [ -n "$pid" ]; then
-        echo "kend is running"
-    else
-        echo "kend is down"
+    status_node
+    if [ ! -z $AUTO_RESTART_NODE ] && [[ $AUTO_RESTART_NODE -eq 1 ]]; then
+        status_auto_restart_daemon
     fi
 }
+
 
 restart() {
     stop
