apply restart daemon script at others in rpm package.

diff --git a/build/rpm/etc/init.d/kpnd b/build/rpm/etc/init.d/kpnd
--- a/build/rpm/etc/init.d/kpnd
+++ b/build/rpm/etc/init.d/kpnd
@@ -21,8 +21,88 @@ kpn=/usr/bin/kpn
 prog=kpnd
 lockfile=${LOCKFILE-/var/lock/subsys/kpnd}
 pidfile=${PIDFILE-/var/run/kpnd.pid}
+auto_restart_daemon_pidfile=/var/run/restart_daemon.pid
 RETVAL=0
 STOP_TIMEOUT=${STOP_TIMEOUT-10}
+
+__pid_run() {
+  __pids_var_run $prog $pidfile
+}
+
+__auto_restart_daemon_pid_run() {
+    unset auto_restart_daemon_pid
+    if [ ! -f $auto_restart_daemon_pidfile ]; then
+        return
+    fi
+    AUTO_RESTART_DAEMON_PID_NUM=$(eval "cat $auto_restart_daemon_pidfile")
+    if [[ ! -z "$AUTO_RESTART_DAEMON_PID_NUM" ]]; then
+        export auto_restart_daemon_pid=$(eval "ps -p $AUTO_RESTART_DAEMON_PID_NUM -o pid=")
+    fi
+}
+#------------------------Related Auto restart daemon functions-----------------------------
+__auto_restart_daemon() {
+    local backOffTime=$AUTO_RESTART_INTERVAL
+    local coeff=2
+    while :
+    do
+        sleep 1
+        __pid_run
+        if [ -z "$pid" ]; then
+            echo "INFO[`date`] node[${PID_NUM}] is down"
+            if [ -f $pidfile ]; then
+                echo "INFO[`date`] remove redundant pid file"
+                rm -f ${lockfile} ${pidfile}
+            fi
+            echo "INFO[`date`] Sleep for backOffTime.... ${backOffTime} seconds."
+            sleep $backOffTime
+            echo "INFO[`date`] -------------------> start network"
+            start_node
+            echo "INFO[`date`] -------------------> start network"
+            backOffTime=$(echo $backOffTime $coeff | awk '{printf "%.1f\n",$1*$2}')
+
+            echo "INFO[`date`] backOffTime = ${backOffTime}, Restarted node pid = ${PID_NUM}"
+            PID_NUM=$(eval "cat $pidfile")
+            echo ""
+        fi
+    done
+}
+
+start_auto_restart_daemon() {
+    __auto_restart_daemon_pid_run
+    if [ -z $auto_restart_daemon_pid ]; then
+        __auto_restart_daemon >> ${LOG_DIR}/restart_daemon.out 2>&1 &
+        disown
+        AUTO_RESTART_DAEMON_PID_NUM=$!
+        AUTO_RESTART_DAEMON_RETVAL=$?
+
+        set +f
+        if [ $AUTO_RESTART_DAEMON_RETVAL = 0 ]; then
+            echo $AUTO_RESTART_DAEMON_PID_NUM > ${auto_restart_daemon_pidfile}
+            echo "Success to start auto restart daemon."
+        else
+            echo "Fail to start auto restart daemon."
+        fi
+    fi
+}
+
+stop_auto_restart_daemon() {
+    echo -n "Shutting down auto restart daemon: "
+    killproc -p ${auto_restart_daemon_pidfile} -d ${STOP_TIMEOUT}
+    RETVAL=$?
+    echo
+    [ $RETVAL = 0 ] && rm -f ${auto_restart_daemon_lockfile} ${auto_restart_daemon_pidfile}
+}
+
+status_auto_restart_daemon() {
+    __auto_restart_daemon_pid_run
+    if [ -n "$auto_restart_daemon_pid" ]; then
+        echo "auto restart daemon is running."
+    else
+        echo "auto restart daemon is down."
+    fi
+}
+
+#------------------------Related to Klaytn node functions-----------------------------
 
 set -f
 OPTIONS=""
@@ -170,7 +250,7 @@ CURRENTFILE=`basename "$0"`
 OPTIONS="$OPTIONS --autorestart.daemon.path $BASEDIR/$CURRENTFILE"
 set +f
 
-start() {
+start_node() {
         echo -n "Starting $prog: "
         if [ ! -d ${LOG_DIR} ]; then
                 mkdir -p ${LOG_DIR}
@@ -195,12 +275,32 @@ start() {
         return $RETVAL
 }
 
-stop() {
+stop_node() {
         echo -n "Shutting down $prog: "
         killproc -p ${pidfile} -d ${STOP_TIMEOUT} $kpn
         RETVAL=$?
         echo
         [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
+}
+
+#--------------------- Public functions --------------------------
+start() {
+    if [ ! -d $LOG_DIR ]; then
+        mkdir -p $LOG_DIR
+    fi
+
+    if [ ! -z $AUTO_RESTART_NODE ] && [[ $AUTO_RESTART_NODE -eq 1 ]]; then
+        start_auto_restart_daemon
+    else
+        start_node
+    fi
+}
+
+stop() {
+    if [ ! -z $AUTO_RESTART_NODE ] && [[ $AUTO_RESTART_NODE -eq 1 ]]; then
+        stop_auto_restart_daemon
+    fi
+    stop_node
 }
 
 case "$1" in
@@ -212,6 +312,9 @@ case "$1" in
         ;;
     status)
         status -p ${pidfile} -l ${lockfile} $kpn
+        if [ ! -z $AUTO_RESTART_NODE ] && [[ $AUTO_RESTART_NODE -eq 1 ]]; then
+            status_auto_restart_daemon
+        fi
         ;;
     restart)
         stop
