SC: add kspn and ksen binary support (#21)
* SC: add kspn and ksen binary support

* SC: fix command option handling

* SC: apply review comments

* SC: remove network configuration for service chain

* SC: remove baobab and cypress options from kspn and ksen

* SC: try rebuild

* SC: try rebuild

* Update cmd/ksen/doc.go

Co-Authored-By: Sangmin Seo (Sam) <sam.seo@groundx.xyz>

* Update build/rpm/main.go

Co-Authored-By: Sangmin Seo (Sam) <sam.seo@groundx.xyz>

* Update cmd/ksen/main.go

Co-Authored-By: Sangmin Seo (Sam) <sam.seo@groundx.xyz>

* Update cmd/kspn/doc.go

Co-Authored-By: Sangmin Seo (Sam) <sam.seo@groundx.xyz>

* Update cmd/kspn/main.go

Co-Authored-By: Sangmin Seo (Sam) <sam.seo@groundx.xyz>

* apply review comments for converting node types

diff --git a/build/rpm/etc/init.d/ksend b/build/rpm/etc/init.d/ksend
--- a/build/rpm/etc/init.d/ksend
+++ b/build/rpm/etc/init.d/ksend
@@ -1,26 +1,26 @@
 #!/bin/bash
 #
-# kpnd         Startup script for the kpn
+# ksend         Startup script for the ksen
 #
 # chkconifg: - 85 15
-# description : kpnd is the Klaytn proxy node daemon
+# description : ksend is the Klaytn endpoint node daemon
 #
-# processname: kpnd
-# config:  /etc/kpnd/conf/kpnd.conf
-# pidfile: /var/run/kpnd.pid
+# processname: ksend
+# config:  /etc/ksend/conf/ksend.conf
+# pidfile: /var/run/ksend.pid
 #
 
 # Source function library.
 . /etc/init.d/functions
 
-if [ -f /etc/kpnd/conf/kpnd.conf ]; then
-        . /etc/kpnd/conf/kpnd.conf
+if [ -f /etc/ksend/conf/ksend.conf ]; then
+        . /etc/ksend/conf/ksend.conf
 fi
 
-kpn=/usr/bin/kpn
-prog=kpnd
-lockfile=${LOCKFILE-/var/lock/subsys/kpnd}
-pidfile=${PIDFILE-/var/run/kpnd.pid}
+ksen=/usr/bin/ksen
+prog=ksend
+lockfile=${LOCKFILE-/var/lock/subsys/ksend}
+pidfile=${PIDFILE-/var/run/ksend.pid}
 RETVAL=0
 STOP_TIMEOUT=${STOP_TIMEOUT-10}
 
@@ -78,26 +78,17 @@ if [[ ! -z $WS_ENABLE ]] && [[ $WS_ENABLE -eq 1 ]]; then
     fi
 fi
 
-# Cypress network => NETWORK_ID is null && NETWORK = "cypress"
-# Baobab network => NETWORK_ID is null && NETWORK = "baobab"
-# Else => private network
+# private network only for Service Chain
 if [[ -z $NETWORK_ID ]]; then
-    if [[ $NETWORK == "baobab" ]]; then
-        OPTIONS="$OPTIONS --baobab"
-    elif [[ $NETWORK == "cypress" ]]; then
-        OPTIONS="$OPTIONS --cypress"
-    else
-        echo
-        echo "[ERROR] network id is not specified and network is not available."
-        echo "Available network: baobab, cypress"
-        exit 1
-    fi
+    echo
+    echo "[ERROR] network id should be specified for Service Chain."
+    exit 1
 else
     OPTIONS="$OPTIONS --networkid $NETWORK_ID"
     echo "[INFO] creating a private network: $NETWORK_ID"
     if [[ ! -z $NETWORK ]]; then
         echo
-        echo "[WARN] ignoring the specified network: $NETWORK"
+        echo "[WARN] ignoring the specified network for Service Chain: $NETWORK"
     fi
 fi
 
@@ -153,6 +144,13 @@ if [ ! -z $LDBCACHESIZE ]; then
     OPTIONS="$OPTIONS --db.leveldb.cache-size $LDBCACHESIZE"
 fi
 
+if [[ ! -z $SC_MAIN_BRIDGE ]] && [[ $SC_MAIN_BRIDGE -eq 1 ]]; then
+    OPTIONS="$OPTIONS --mainbridge --mainbridgeport $SC_MAIN_BRIDGE_PORT"
+    if [[ ! -z $SC_MAIN_BRIDGE_INDEXING ]] && [[ $SC_MAIN_BRIDGE_INDEXING -eq 1 ]]; then
+        OPTIONS="$OPTIONS --childchainindexing"
+    fi
+fi
+
 if [[ ! -z $NO_DISCOVER ]] && [[ $NO_DISCOVER -eq 1 ]]; then
     OPTIONS="$OPTIONS --nodiscover"
 fi
@@ -176,7 +174,7 @@ start() {
         [ -n "$pid" ] && echo && return
 
         set -f
-        $kpn $OPTIONS >> ${LOG_DIR}/kpnd.out 2>&1 &
+        $ksen $OPTIONS >> ${LOG_DIR}/ksend.out 2>&1 &
         RETVAL=$?
         PIDNUM=$!
         set +f
@@ -193,7 +191,7 @@ start() {
 
 stop() {
         echo -n "Shutting down $prog: "
-        killproc -p ${pidfile} -d ${STOP_TIMEOUT} $kpn
+        killproc -p ${pidfile} -d ${STOP_TIMEOUT} $ksen
         RETVAL=$?
         echo
         [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
@@ -207,7 +205,7 @@ case "$1" in
         stop
         ;;
     status)
-        status -p ${pidfile} -l ${lockfile} $kpn
+        status -p ${pidfile} -l ${lockfile} $ksen
         ;;
     restart)
         stop
diff --git a/build/rpm/etc/init.d/kspnd b/build/rpm/etc/init.d/kspnd
--- a/build/rpm/etc/init.d/kspnd
+++ b/build/rpm/etc/init.d/kspnd
@@ -1,26 +1,26 @@
 #!/bin/bash
 #
-# kpnd         Startup script for the kpn
+# kspnd         Startup script for the kspn
 #
 # chkconifg: - 85 15
-# description : kpnd is the Klaytn proxy node daemon
+# description : kspnd is the Klaytn proxy node daemon
 #
-# processname: kpnd
-# config:  /etc/kpnd/conf/kpnd.conf
-# pidfile: /var/run/kpnd.pid
+# processname: kspnd
+# config:  /etc/kspnd/conf/kspnd.conf
+# pidfile: /var/run/kspnd.pid
 #
 
 # Source function library.
 . /etc/init.d/functions
 
-if [ -f /etc/kpnd/conf/kpnd.conf ]; then
-        . /etc/kpnd/conf/kpnd.conf
+if [ -f /etc/kspnd/conf/kspnd.conf ]; then
+        . /etc/kspnd/conf/kspnd.conf
 fi
 
-kpn=/usr/bin/kpn
-prog=kpnd
-lockfile=${LOCKFILE-/var/lock/subsys/kpnd}
-pidfile=${PIDFILE-/var/run/kpnd.pid}
+kspn=/usr/bin/kspn
+prog=kspnd
+lockfile=${LOCKFILE-/var/lock/subsys/kspnd}
+pidfile=${PIDFILE-/var/run/kspnd.pid}
 RETVAL=0
 STOP_TIMEOUT=${STOP_TIMEOUT-10}
 
@@ -78,26 +78,17 @@ if [[ ! -z $WS_ENABLE ]] && [[ $WS_ENABLE -eq 1 ]]; then
     fi
 fi
 
-# Cypress network => NETWORK_ID is null && NETWORK = "cypress"
-# Baobab network => NETWORK_ID is null && NETWORK = "baobab"
-# Else => private network
+# private network only for Service Chain
 if [[ -z $NETWORK_ID ]]; then
-    if [[ $NETWORK == "baobab" ]]; then
-        OPTIONS="$OPTIONS --baobab"
-    elif [[ $NETWORK == "cypress" ]]; then
-        OPTIONS="$OPTIONS --cypress"
-    else
-        echo
-        echo "[ERROR] network id is not specified and network is not available."
-        echo "Available network: baobab, cypress"
-        exit 1
-    fi
+    echo
+    echo "[ERROR] network id should be specified for Service Chain."
+    exit 1
 else
     OPTIONS="$OPTIONS --networkid $NETWORK_ID"
     echo "[INFO] creating a private network: $NETWORK_ID"
     if [[ ! -z $NETWORK ]]; then
         echo
-        echo "[WARN] ignoring the specified network: $NETWORK"
+        echo "[WARN] ignoring the specified network for Service Chain: $NETWORK"
     fi
 fi
 
@@ -176,7 +167,7 @@ start() {
         [ -n "$pid" ] && echo && return
 
         set -f
-        $kpn $OPTIONS >> ${LOG_DIR}/kpnd.out 2>&1 &
+        $kspn $OPTIONS >> ${LOG_DIR}/kspnd.out 2>&1 &
         RETVAL=$?
         PIDNUM=$!
         set +f
@@ -193,7 +184,7 @@ start() {
 
 stop() {
         echo -n "Shutting down $prog: "
-        killproc -p ${pidfile} -d ${STOP_TIMEOUT} $kpn
+        killproc -p ${pidfile} -d ${STOP_TIMEOUT} $kspn
         RETVAL=$?
         echo
         [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
@@ -207,7 +198,7 @@ case "$1" in
         stop
         ;;
     status)
-        status -p ${pidfile} -l ${lockfile} $kpn
+        status -p ${pidfile} -l ${lockfile} $kspn
         ;;
     restart)
         stop
